FROM golang:1.24-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /crawler ./cmd/crawler

FROM gcr.io/distroless/static

COPY --from=build /crawler /crawler

ENTRYPOINT ["/crawler"]
